### ISSUE TITLE
Functions defined on the test class not available when test runs

### ISSUE THREAD

**Issue by jviney** [mike-north/qunit-decorators#35]
```
import { EmberTest } from 'ember-qunit-decorators/test-support'
import { suite, test } from 'qunit-decorators'

@suite('SimpleTest')
export class SimpleTest extends EmberTest {
  constructor() {
    super(...arguments)
    this.myFunction() // works fine
  }

  public myFunction() {
    return true
  }

  @test
  public testOne(assert: Assert) {
    this.myFunction() // TypeError
  }
}
```

Results in the error: `TypeError: this.myFunction is not a function`.

```
ember-qunit-decorators 1.4.0
qunit-decorators 1.1.3
ember-source 3.4.6
ember-cli-qunit 4.4.0
ember-qunit 3.5.3
ember-cli-typescript 1.5.0
```

It looks like the `this` inside `testOne()` is different from inside the constructor. Is the `@test` decorator not preserving `this` correctly?

**Comment by mike-north** [comment]
Qunit has a very special way of treating the lexical scope within a test method. From their docs:

> The module’s callback is invoked with the test environment as its `this` context, with the environment’s properties copied to the module’s tests, hooks, and nested modules.

What you see as the current behavior is very close to the official QUnit behavior, with the exception that member data is treated more in line with what consumers are likely to expect from classes because an instance of your test suite class is merged into the normal QUnit thing they call the "test environment".

https://github.com/mike-north/qunit-decorators/blob/d72b131d973582777b8a634a4ad1e80d0097614d/src/index.ts#L78

I see there being a need to deviate from the QUnit behavior a little bit, in particular, this aspect of QUnit's test environment would be _really_ unexpected in a JS/TS class-like situation. Again, from their docs:

>  ... changes on tests’ this are not preserved between sibling tests, where this will be reset to the initial value for each test.

Additionally, the problem you're running into results from the fact that, in the above code snippet, only the _instance's_ properties are shallow-copied into the QUnit test environment, and w/ JS/TS classes, methods still live on the prototype. 

I'm fixing this by making a more rigorous copy of stuff from each suite's class into the test environment, walking all the way up the prototype chain. This should be cheap, as I can't imagine elaborate inheritance hierarchies in test suites, and any expensive objects (i.e., functions) aren't deep copied -- the test environment just gets a reference to them.

---

If this causes problematic inheritance stuff in the future, I reserve the right to walk this change back (or limit inheritance w/in suite classes) in a future major release.
